version: '3'

services:
  app:
    image: 'api'
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/app
    working_dir: /app
    command: ['gradle', 'bootRun']
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres_db:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
